# cli1: kubectl apply -f service.yaml
# cli2: kubectl get services
# cli3: minikube service backend 

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app
    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    # - protocol: TCP
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer