# docker-compose.yml
services:
  agent-dev:
    build: .
    image: fastapi-agent:1 # ğŸ’¡ ì´ë¯¸ì§€ë¥¼ ì§ì ‘ ëª…ì‹œ
    volumes:
      - ..:/workspaces/agent:cached

    
    # ğŸ’¡ ì´ ë‘ ì¤„ì„ ì¶”ê°€í•˜ì—¬ ëŒ€í™”ì‹ ì‰˜ì„ ìœ ì§€í•©ë‹ˆë‹¤.
    stdin_open: true # í‘œì¤€ ì…ë ¥ì„ ì—½ë‹ˆë‹¤.
    tty: true        # TTY (í„°ë¯¸ë„)ì„ í• ë‹¹í•©ë‹ˆë‹¤